project:
  type: website

website:
  title: Clemens Brunner
  navbar:
    left:
      - href: index.qmd
      - href: blog.qmd
    right:
      - text: "{{< ai orcid >}}"
        href: https://orcid.org/0000-0002-6030-2233
      - text: "{{< fa brands mastodon >}}"
        href: https://scholar.social/web/@cbrnr
      - icon: github
        href: https://github.com/cbrnr
      - icon: envelope-fill
        href: mailto:clemens.brunner@gmail.com
  page-footer:
    center: © Clemens Brunner

format:
  html:
    page-layout: full
    theme:
      light: [custom.scss, flatly]
      dark: [custom.scss, darkly]
    css: styles.css
